AllCops:
  TargetRubyVersion: 3.2
Style/Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true